//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservoirVolume
    {
        public int recordID { get; set; }
        public int reservoirID { get; set; }
        public System.DateTime recordDate { get; set; }
        public decimal volumeToday { get; set; }
        public decimal volumeLastYear { get; set; }
        public decimal averageVolume { get; set; }
    
        public virtual Reservoir Reservoir { get; set; }
    }
}
